#server:
#  port: 8888
#spring:
#  application:
#    name: config-server
#  cloud:
#    config:
#      server:
#        default-label: main
#        git:
#          uri: https://github.com/MehmetSimsek33/config-servers+
#  profiles:
#    active: dev